INSERT INTO public.document_types (id,sunat_code,name_document) VALUES
    (1,'01','FACTURA'),
    (2,'03','BOLETA DE VENTA'),
    (3,'07','NOTA DE CREDITO'),
    (4,'08','NOTA DE DEBITO'),
    (5,'09','GUIA DE REMISION REMITENT'),
    (6,'12','TICKET DE MAQUINA REGISTRADORA'),
    (8,'18','DOCUMENTO EMITIDOS POR LA AFP'),
    (9,'31','GUIA DE REMISION TRANSPORTISTA'),
    (10,'56','COMPROBANTE DE PAGO SEAE'),
    (7,'13','DOCUMENTO EMITIDO POR BANCOS, INSTITUCIOINES FINANCIERAS, CREDITICIAS Y DE SEGUROS QUE SE ENCUENTRAN BAJO EL CONTROL DE LA SUPERINTENDENCIA DE BANCA Y SEGUROS'),
    (11,'00','Otros (Interno, Varios, Sin Comprobante)');
